openapi: 3.1.0
info:
  title: Jira Business Ops Assistant
  description: Create internal Business Operations requests in Jira via Service Desk.
  version: 1.0.0

servers:
  - url: https://api.atlassian.com/ex/jira/{cloud_id}/rest/servicedeskapi
    description: Jira Cloud Service Desk API (OAuth-compatible)
    variables:
      cloud_id:
        default: your-cloud-id-here  # Replace with actual value if you want to test locally

paths:
  /request:
    post:
      operationId: createServiceRequest
      summary: Create a new Business Operations request in Jira Service Management.
      description: Submits a request to a service desk using Jira Service Management's customer-facing API.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceDeskId:
                  type: string
                  example: "1"
                  description: ID of the service desk project
                requestTypeId:
                  type: string
                  example: "16"
                  description: ID of the request type
                requestFieldValues:
                  type: object
                  additionalProperties: true
                  description: Field values required for the request (e.g., summary, description)
              required:
                - serviceDeskId
                - requestTypeId
                - requestFieldValues
      responses:
        '201':
          description: Request created successfully
        '400':
          description: Bad request (missing fields or invalid data)
        '401':
          description: Unauthorized (invalid or missing credentials)

components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:jira-user: Read user info
            read:jira-service-management-request: Read JSM requests
            write:jira-service-management-request: Create JSM requests

security:
  - oauth:
      - read:jira-user
      - read:jira-service-management-request
      - write:jira-service-management-request

